import type { Attack } from '../../types';
import { queryFactorDB, formatFactorDBResult } from '../../utils/factordb';
import { isqrt } from '../../utils/bigint';

export const advancedAttacks: Attack[] = [
  {
    id: 'roca',
    name: 'ROCA Vulnerability',
    description: 'Exploits primes generated by Infineon\'s ROCA-vulnerable key generation (p = k·M + (65537^i mod M)).',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})

# ROCA: Return of Coppersmith's Attack
# Primes of form p = k*M + (65537^i mod M)
# M = product of first several primes

print("ROCA vulnerability check")
print(f"n = {n}")
print()

# Try small M values (M_3, M_5, M_7, ...)
primes_list = [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]

found = False
for num_primes in range(1, len(primes_list) + 1):
    M = prod(primes_list[:num_primes])
    if M > 2**32:
        break
    
    # Compute possible remainders: 65537^i mod M
    order = M
    remainders = set()
    remainders.add(1)  # 65537^0 mod M = 1
    a = 1
    for _ in range(order):
        a = (a * 65537) % M
        remainders.add(a)
        if a == 1:
            break
    
    # Check if n mod M is product of two remainders
    n_mod = n % M
    for r1 in remainders:
        if n_mod * inverse_mod(r1, M) % M in remainders:
            print(f"Possible match with M = product of first {num_primes} primes")
            print(f"M = {M}")
            print(f"n mod M = {n_mod}")
            print(f"Found compatible remainders: r1 = {r1}")
            found = True
            break
    if found:
        break

if found:
    print()
    print("VULNERABLE: n appears to use ROCA-generated primes.")
    print("Use Coppersmith's method to recover p.")
    print()
    
    # Coppersmith's method for small M
    # p = k*M + r, where r is known remainder
    # We search for k using Coppersmith
    r = r1
    R.<x> = PolynomialRing(ZZ)
    f = M*x + r

    # Try to find small root
    # p <= sqrt(n), so k <= sqrt(n)/M
    bound = ceil(sqrt(n) / M)
    print(f"Searching for k with bound ~{bound}")

    # Use Sage's small_roots
    f_mod = f.change_ring(Zmod(n))
    roots = f_mod.small_roots(X=bound, beta=0.5, epsilon=0.05)
    
    if roots:
        k = int(roots[0])
        p = int(M * k + r)
        if n % p == 0:
            q = n // p
            print(f"SUCCESS! Factor found:")
            print(f"p = {p}")
            print(f"q = {q}")
            print(f"Verification: p * q = {p * q}")
        else:
            print("Root found but does not divide n. Try different parameters.")
    else:
        print("No small root found. n may use a larger M value.")
        print("Try using the full ROCA implementation with larger prime bases.")
else:
    print("n does NOT appear to be ROCA-vulnerable for small M values.")
    print("The primes were likely not generated by Infineon's library.")
`,
    proof: `\\textbf{Theorem:} RSA primes generated by Infineon's ROCA-vulnerable library (v1.01.006–v1.02.008) have the form \\(p = k \\cdot M + (65537^{i} \\bmod M)\\), enabling factorization via Coppersmith's method.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Modulus \\(n = pq\\) where at least one prime was generated by Infineon's library
\\item \\(M = \\prod_{j=1}^{m} p_j\\) — product of first \\(m\\) small primes
\\item The remainder set \\(\\mathcal{R} = \\{65537^i \\bmod M : i \\geq 0\\}\\) must be small enough to enumerate
\\item \\(M > n^{1/4}\\) for Coppersmith's method to succeed
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
p &= k \\cdot M + r_1, \\quad r_1 \\in \\mathcal{R} \\\\
q &= k' \\cdot M + r_2, \\quad r_2 \\in \\mathcal{R} \\\\
n &= pq \\equiv r_1 \\cdot r_2 \\pmod{M} \\\\
f(x) &= M \\cdot x + r_1 \\equiv 0 \\pmod{p} \\\\
|x_0| = k &< \\frac{\\sqrt{n}}{M} < p^{1/\\delta} \\quad (\\delta = \\deg f = 1) \\\\
\\text{Coppersmith recovers } x_0 = k &\\implies p = M \\cdot k + r_1 \\qed
\\end{align*}

\\textbf{Explanation:} The attack fingerprints \\(n \\bmod M\\) against products of known remainders. A match identifies the correct \\(M\\) and remainder \\(r_1\\), then Coppersmith's method recovers \\(k\\) from the linear polynomial \\(f(x) = Mx + r_1\\) modulo \\(p\\).

\\textbf{References:} M. Nemec et al., "The Return of Coppersmith's Attack: Practical Factorization of Widely Used RSA Moduli", CCS 2017; https://crocs.fi.muni.cz/roca`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'nitros',
    name: 'Nitros / ROCA Variant',
    description: 'Extended ROCA attack with multiple prime forms and generalized remainders.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'base', label: 'Base (default 65537)', placeholder: '65537', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
base = Integer(${vals.base || '65537'})

print("Nitros / Extended ROCA attack")
print(f"n = {n}")
print(f"base = {base}")
print()

# Try multiple prime bases for M
prime_sets = [
    [3, 5, 7, 11, 13, 17, 19, 23],
    [3, 5, 7, 11, 13, 17, 19, 23, 29, 31],
    [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41],
]

found = False
for primes_subset in prime_sets:
    M = prod(primes_subset)
    
    # Compute remainders
    remainders = set()
    remainders.add(1)  # base^0 mod M = 1
    a = 1
    for _ in range(M):
        a = (a * base) % M
        remainders.add(a)
        if a == 1:
            break
    
    n_mod = n % M
    
    # Check if n_mod factors into two remainders
    for r1 in remainders:
        r2 = n_mod * inverse_mod(r1, M) % M
        if r2 in remainders:
            print(f"Match found with M = {M}")
            print(f"r1 = {r1}, r2 = {r2}")
            print(f"Verification: r1 * r2 mod M = {(r1 * r2) % M} (n mod M = {n_mod})")
            found = True
            
            # Try Coppersmith
            R.<x> = PolynomialRing(ZZ)
            f = M*x + r1
            bound = ceil(sqrt(n) / M)
            
            f_mod = f.change_ring(Zmod(n))
            roots = f_mod.small_roots(X=bound, beta=0.5, epsilon=0.05)
            
            if roots:
                k = int(roots[0])
                p = int(M * k + r1)
                if n % p == 0:
                    q = n // p
                    print(f"SUCCESS! p = {p}, q = {q}")
                    print(f"Verification: p * q = {p * q}")
                else:
                    print(f"Root found but doesn't divide n. Trying r2...")
                    f2 = M*x + r2
                    roots2 = f2.change_ring(Zmod(n)).small_roots(X=bound, beta=0.5, epsilon=0.05)
                    if roots2:
                        k2 = int(roots2[0])
                        p2 = int(M * k2 + r2)
                        if n % p2 == 0:
                            print(f"SUCCESS! p = {p2}, q = {n // p2}")
            break
    if found:
        break

if not found:
    print("No ROCA/Nitros pattern detected for tested M values.")
`,
    proof: `\\textbf{Theorem:} The Nitros attack generalizes ROCA to primes of the form \\(p = k \\cdot M + (a^{i} \\bmod M)\\) for arbitrary base \\(a\\).

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Modulus \\(n = pq\\) with at least one prime of the generalized form
\\item Base \\(a\\) with \\(\\gcd(a, M) = 1\\) (default: \\(a = 65537\\))
\\item \\(M\\) — product of a subset of small primes
\\item Remainder set \\(\\mathcal{R} = \\{a^i \\bmod M : i \\geq 0\\}\\) must be enumerable
\\item \\(M > n^{1/4}\\) for Coppersmith's method
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
p &= k \\cdot M + r_1, \\quad r_1 \\in \\mathcal{R} \\\\
n &\\equiv r_1 \\cdot r_2 \\pmod{M}, \\quad r_2 \\in \\mathcal{R} \\\\
r_2 &\\equiv n \\cdot r_1^{-1} \\pmod{M} \\\\
f(x) &= M \\cdot x + r_1 \\equiv 0 \\pmod{p} \\\\
|x_0| = k &< \\frac{\\sqrt{n}}{M} < p^{1/\\delta} \\quad (\\delta = 1) \\\\
\\text{Coppersmith recovers } x_0 = k &\\implies p = M \\cdot k + r_1 \\qed
\\end{align*}

\\textbf{Explanation:} The algorithm tests multiple prime subsets for \\(M\\) and configurable base \\(a\\). Once a matching remainder pair \\((r_1, r_2)\\) is found, Coppersmith's method recovers \\(k\\). Both \\(r_1\\) and \\(r_2\\) are tried as candidate remainders.

\\textbf{References:} Nemec et al., CCS 2017; extended analysis in subsequent ROCA research`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'factordb-lookup',
    name: 'FactorDB Lookup',
    description: 'Checks if n has known factors from precomputed factorization databases.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
    ],
    frontendCheck: async (vals: Record<string, string>) => {
      try {
        const result = await queryFactorDB(vals.n);
        if (result.status === "FF" && result.factors && result.factors.length >= 2) {
          return formatFactorDBResult(result);
        }
        return null;
      } catch {
        return null;
      }
    },
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})

print(f"Checking if n = {n} has known factors")
print()

# Trial division with small primes
print("Step 1: Trial division with small primes...")
small_primes = primes(10000)
for p in small_primes:
    if n % p == 0:
        q = n // p
        print(f"Found small factor: p = {p}")
        print(f"q = {q}")
        if is_prime(q):
            print("q is prime. Factorization complete!")
        else:
            print(f"q is composite. Further factorization needed.")
            print(f"q factors: {factor(q)}")
        break
else:
    print("No factors found below 10000.")

# Try ECM
print()
print("Step 2: ECM factorization...")
try:
    factors = ecm.factor(n, max_steps=100)
    if factors and len(factors) > 1:
        print(f"ECM found factors: {factors}")
        flist = list(factors)
        if len(flist) == 2:
            p, q = flist[0][0], flist[1][0]
            print(f"p = {p}")
            print(f"q = {q}")
        else:
            print(f"Complete factorization: {factors}")
    else:
        print("ECM did not find factors within step limit.")
except:
    print("ECM failed.")

# Try Pollard's rho
print()
print("Step 3: Pollard's rho...")
try:
    f = pollard_rho(n)
    if f and f != n:
        print(f"Pollard's rho found: {f}")
        print(f"Other factor: {n // f}")
    else:
        print("Pollard's rho did not find a factor.")
except:
    print("Pollard's rho failed.")
`,
    proof: `\\textbf{Theorem:} Many RSA moduli from CTF challenges and weak key generation have been pre-factored and stored in public databases.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Modulus $n$ to check against known factorizations
\\item Network access to FactorDB API (or CORS proxy)
\\item Fallback: trial division primes up to bound $B$, ECM curves, Pollard's rho iterations
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
\\text{Query:} &\\quad \\text{factordb.com/api}?query = n \\\\
\\text{Response:} &\\quad \\{ \\text{status}, \\text{factors} = [p_1, p_2, \\ldots, p_k] \\} \\\\
\\text{Verify:} &\\quad \\prod_{i=1}^{k} p_i = n \\\\
\\text{Fallback 1:} &\\quad \\exists\\, p \\in \\text{primes}(B) : n \\bmod p = 0 \\\\
\\text{Fallback 2:} &\\quad \\text{ECM}(n, \\text{curves}) \\rightarrow [p, q] \\\\
\\text{Fallback 3:} &\\quad \\text{PollardRho}(n) \\rightarrow p, \\quad q = n / p
\\end{align*}

\\textbf{Explanation:} FactorDB returns pre-computed factorizations instantly for known moduli. If the database has no entry, the SageMath fallback runs trial division, ECM, and Pollard's rho sequentially.

\\textbf{References:} https://factordb.com; RsaCtfTool project`,
    priority: 'low',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'known-plaintext',
    name: 'Known Plaintext Attack',
    description: 'Recovers RSA parameters when the plaintext structure is partially known.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '65537', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
      { name: 'known_prefix', label: 'Known plaintext prefix (optional)', placeholder: 'e.g., flag{', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '65537'})
c = Integer(${vals.c})
known_prefix = "${vals.known_prefix || ''}"

print("Known plaintext attack on RSA")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
if known_prefix:
    print(f"Known prefix: '{known_prefix}'")
print()

# Convert known prefix to integer
if known_prefix:
    prefix_bytes = known_prefix.encode('utf-8')
    prefix_int = Integer(int.from_bytes(prefix_bytes, 'big'))
    prefix_len = len(prefix_bytes)
    
    print(f"Prefix as integer: {prefix_int}")
    print(f"Prefix byte length: {prefix_len}")
    print()
    
    # The plaintext m has form: m = prefix_int * 256^k + unknown
    # where k is the number of unknown bytes
    # c = m^e mod n
    # We need to find m such that m^e = c (mod n) and m starts with prefix
    
    # Estimate total message length
    n_bits = n.nbits()
    max_bytes = n_bits // 8
    
    # Try brute force for small unknown portions
    unknown_bytes = max_bytes - prefix_len
    print(f"Estimated message length: {max_bytes} bytes")
    print(f"Unknown portion: {unknown_bytes} bytes")
    print()
    
    if unknown_bytes <= 4:
        print(f"Brute forcing {unknown_bytes} unknown byte(s)...")
        bound = 256^unknown_bytes
        for k in range(bound):
            m = prefix_int * (256^unknown_bytes) + k
            if power_mod(m, e, n) == c:
                print(f"FOUND! m = {m}")
                print(f"m as bytes: {bytes.fromhex(hex(m)[2:] if len(hex(m)) % 2 == 0 else '0' + hex(m)[2:])}")
                break
        else:
            print("Brute force exhausted without finding match.")
    elif unknown_bytes <= 10:
        print(f"Using Coppersmith's method for {unknown_bytes} unknown bytes...")
        # m = prefix * 2^k + x, where x is small
        R.<x> = PolynomialRing(Zmod(n))
        shift = 256^unknown_bytes
        f = (prefix_int * shift + x)^e - c
        roots = f.small_roots(X=shift, beta=1.0, epsilon=0.01)
        if roots:
            x = int(roots[0])
            m = prefix_int * shift + x
            print(f"FOUND! m = {m}")
            try:
                print(f"m as bytes: {bytes.fromhex(hex(m)[2:].zfill(max_bytes*2))}")
            except:
                print(f"m as hex: {hex(m)}")
        else:
            print("Coppersmith's method did not find a solution.")
            print("Try increasing epsilon or the unknown portion may be too large.")
    else:
        print(f"Unknown portion ({unknown_bytes} bytes) too large for direct attack.")
        print("Consider: lattice attacks, partial key recovery, or other methods.")
else:
    print("No known prefix provided.")
    print("Try: small e attack, common modulus attack, or factorization methods.")
`,
    proof: `\\textbf{Theorem:} Partial knowledge of the plaintext \\(m\\) enables RSA decryption via Coppersmith's method for small unknown portions.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Public key \\((n, e)\\) and ciphertext \\(c\\)
\\item Known prefix \\(m_0\\) such that \\(m = m_0 \\cdot 2^k + x\\) with unknown \\(x < 2^k\\)
\\item \\(k\\) — number of unknown bits, determines attack feasibility
\\item For brute force: \\(k \\leq 32\\) (4 bytes); for Coppersmith: \\(k \\lesssim \\frac{\\log_2 n}{e}\\)
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
m &= m_0 \\cdot 2^k + x, \\quad |x| < X = 2^k \\\\
c &\\equiv m^e \\pmod{n} \\\\
f(x) &= (m_0 \\cdot 2^k + x)^e - c \\equiv 0 \\pmod{n} \\\\
|x| &< n^{1/e} \\implies \\text{Coppersmith recovers } x \\\\
m &= m_0 \\cdot 2^k + x \\qed
\\end{align*}

\\textbf{Explanation:} The known prefix fixes the high-order bits of \\(m\\). Coppersmith's method finds the small unknown portion \\(x\\) as a root of the polynomial \\(f(x)\\) modulo \\(n\\). For very small unknowns (\\(\\leq 4\\) bytes), brute force is faster.

\\textbf{References:} D. Coppersmith, "Small Solutions to Polynomial Equations", 1997; May, "New RSA Vulnerabilities Using Lattice Reduction Methods", 2003`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.c),
  },
  {
    id: 'small-public-exp',
    name: 'Small Public Exponent Analysis',
    description: 'Detects and exploits very small public exponent values (e = 3, 5, 17).',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '3', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '3'})
c = Integer(${vals.c})

print(f"Small public exponent analysis")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
print()

# Check if e is small
if e >= 100:
    print(f"e = {e} is not considered 'small' for this attack.")
    print("This attack is effective for e in {3, 5, 17}.")
    print("Try other attack methods.")
else:
    print(f"e = {e} is small. Checking for vulnerabilities...")
    print()
    
    # Attack 1: e-th root (m^e < n)
    print("Attack 1: e-th root attack (m^e < n)")
    m_root = c.nth_root(e, truncate_mode='floor')
    if m_root^e == c:
        print(f"SUCCESS! c is a perfect {e}-th power.")
        print(f"m = {m_root}")
        try:
            m_bytes = bytes.fromhex(hex(m_root)[2:].zfill(2))
            print(f"m as text: {m_bytes.decode('utf-8', errors='replace')}")
        except:
            print(f"m as hex: {hex(m_root)}")
    else:
        print(f"c is not a perfect {e}-th power over integers.")
        print("m^e >= n, so modular reduction occurred.")
    print()
    
    # Attack 2: Hastad broadcast (need multiple (n, c) pairs)
    print("Attack 2: Hastad broadcast note")
    print("If the SAME message m was encrypted with e = 3")
    print("under 3 DIFFERENT moduli n1, n2, n3, then:")
    print("  m = CRT(c1, c2, c3)^(1/3) over integers")
    print("Provide additional (n, c) pairs to attempt this attack.")
    print()
    
    # Attack 3: Franklin-Reiter related message
    print("Attack 3: Franklin-Reiter related message note")
    print("If two ciphertexts c1 = m^e and c2 = (m + delta)^e")
    print("are known with the same (n, e), then m can be recovered.")
    print("Provide a second ciphertext to attempt this attack.")
`,
    proof: `\\textbf{Theorem:} RSA with small public exponent \\(e \\in \\{3, 5, 17\\}\\) is vulnerable to e-th root, Hastad broadcast, and Franklin-Reiter attacks.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Public key \\((n, e)\\) with \\(e < 100\\) and ciphertext \\(c\\)
\\item For e-th root: \\(m^e < n\\) (no modular reduction occurred)
\\item For Hastad: \\(e\\) ciphertexts \\(c_i = m^e \\bmod n_i\\) under distinct moduli
\\item For Franklin-Reiter: two ciphertexts with known linear relation between plaintexts
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
\\text{e-th root:} &\\quad m^e < n \\implies c = m^e \\implies m = \\sqrt[e]{c} \\\\
\\text{Hastad:} &\\quad c_i \\equiv m^e \\pmod{n_i}, \\; i = 1, \\ldots, e \\\\
&\\quad C \\equiv m^e \\pmod{N}, \\quad N = \\prod_{i=1}^{e} n_i \\\\
&\\quad m^e < N \\implies m = \\sqrt[e]{C} \\\\
\\text{Franklin-Reiter:} &\\quad c_1 \\equiv m^e \\pmod{n}, \\quad c_2 \\equiv (am + b)^e \\pmod{n} \\\\
&\\quad \\gcd(x^e - c_1, \\; (ax + b)^e - c_2) = x - m \\quad \\text{over } \\mathbb{Z}_n \\qed
\\end{align*}

\\textbf{Explanation:} The e-th root attack works when the message is small enough that encryption doesn't wrap modulo \\(n\\). Hastad's broadcast attack combines \\(e\\) encryptions of the same message under different moduli via CRT. Franklin-Reiter exploits known linear relations between two encrypted messages.

\\textbf{References:} Hastad, "Solving linear equations by means of lattice reductions", 1988; Franklin & Reiter, "The relation between short exponents and related-message attacks", 1996`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.e && p.c),
  },
  {
    id: 'multi-prime-gcd',
    name: 'Multi-Prime GCD',
    description: 'Finds shared prime factors across multiple RSA moduli (batch GCD attack).',
    category: 'Advanced',
    inputs: [
      { name: 'moduli_list', label: 'Moduli (one per line)', placeholder: 'Enter multiple moduli, one per line...', multiline: true, rows: 6 },
    ],
    sageTemplate: (vals: Record<string, string>) => `# Parse moduli
moduli_str = """${vals.moduli_list}""".strip()
moduli = [Integer(x.strip()) for x in moduli_str.split('\\n') if x.strip()]

print(f"Multi-Prime GCD attack on {len(moduli)} moduli")
print()

if len(moduli) < 2:
    print("Need at least 2 moduli for this attack.")
else:
    # Batch GCD: compute product of all moduli, then GCD each with product/others
    print("Computing batch GCD...")
    print()
    
    found_any = False
    for i in range(len(moduli)):
        ni = moduli[i]
        for j in range(i + 1, len(moduli)):
            nj = moduli[j]
            g = gcd(ni, nj)
            if g > 1 and g < ni:
                found_any = True
                print(f"SHARED FACTOR FOUND between moduli {i+1} and {j+1}!")
                print(f"gcd(n{i+1}, n{j+1}) = {g}")
                print(f"n{i+1} = {ni}")
                print(f"  p = {g}")
                print(f"  q = {ni // g}")
                print(f"n{j+1} = {nj}")
                print(f"  p' = {g}")
                print(f"  q' = {nj // g}")
                print()
    
    if not found_any:
        print("No shared factors found among the provided moduli.")
        print()
        print("This could mean:")
        print("  1. All moduli use independently generated primes (good practice)")
        print("  2. The shared factors are not between the provided pairs")
        print("  3. More moduli are needed to find common factors")
        print()
        print("Note: In real-world scans, ~0.2% of RSA certificates share factors")
        print("due to poor entropy during key generation.")
`,
    proof: `\\textbf{Theorem:} RSA moduli generated with insufficient entropy may share prime factors, enabling factorization via pairwise GCD.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item At least 2 moduli $n_1, n_2, \\ldots, n_k$ to compare
\\item Each $n_i = p_i \\cdot q_i$ where $p_i, q_i$ are primes
\\item At least one pair shares a factor: $\\exists\\, i \\neq j : \\gcd(n_i, n_j) > 1$
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
g_{ij} &= \\gcd(n_i, n_j) \\\\
g_{ij} &> 1 \\implies \\exists\\, p : p \\mid n_i \\land p \\mid n_j \\\\
n_i &= g_{ij} \\cdot \\frac{n_i}{g_{ij}} \\\\
n_j &= g_{ij} \\cdot \\frac{n_j}{g_{ij}} \\\\
\\text{Batch optimization:} &\\quad P = \\prod_{i=1}^{k} n_i, \\quad g_i = \\gcd\\!\\left(n_i, \\frac{P}{n_i^2}\\right)
\\end{align*}

\\textbf{Explanation:} When two moduli share a prime factor, their GCD reveals that factor immediately. The batch variant computes the product of all moduli once, then checks each $n_i$ against $P/n_i^2$, reducing $O(k^2)$ pairwise GCDs to $O(k)$.

\\textbf{References:} N. Heninger et al., "Mining Your Ps and Qs: Detection of Widespread Weak Keys in Network Devices", USENIX Security 2012`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => {
      const vals = (p.moduli_list || '').trim();
      if (!vals) return false;
      return vals.split('\n').filter(x => x.trim()).length >= 2;
    },
  },
  {
    id: 'phi-leak',
    name: 'Phi(n) Leak',
    description: 'Recovers prime factors when Euler\'s totient function phi(n) is leaked.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'phi', label: 'phi(n) (Euler totient)', placeholder: 'Enter phi(n)...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
phi = Integer(${vals.phi})

print("Phi(n) leak attack")
print(f"n = {n}")
print(f"phi(n) = {phi}")
print()

# For n = p*q: phi(n) = (p-1)(q-1) = pq - p - q + 1 = n - p - q + 1
# So: p + q = n - phi + 1
# And: p * q = n
# We solve: x^2 - (p+q)x + pq = 0
# i.e.: x^2 - (n - phi + 1)x + n = 0

sum_pq = n - phi + 1
print(f"p + q = {sum_pq}")
print(f"p * q = {n}")
print()

# Solve quadratic: x^2 - sum_pq * x + n = 0
discriminant = sum_pq^2 - 4*n
print(f"Discriminant = {discriminant}")

if discriminant < 0:
    print("ERROR: Negative discriminant. phi(n) is inconsistent with n.")
elif discriminant == 0:
    print("ERROR: p = q. n is a perfect square (not valid RSA).")
else:
    sqrt_disc = isqrt(discriminant)
    if sqrt_disc^2 == discriminant:
        p = (sum_pq - sqrt_disc) // 2
        q = (sum_pq + sqrt_disc) // 2
        print(f"SUCCESS! Factors recovered:")
        print(f"p = {p}")
        print(f"q = {q}")
        print(f"Verification: p * q = {p * q}")
        print(f"Verification: (p-1)*(q-1) = {(p-1)*(q-1)}")

        try:
            e_val = Integer(${vals.e || '0'})
            if e_val > 0:
                d = inverse_mod(e_val, phi)
                print(f"d (private exponent) = {d}")
        except:
            pass
    else:
        print(f"Discriminant is not a perfect square: {discriminant}")
        print("phi(n) may be incorrect, or n has more than 2 prime factors.")
`,
    frontendCheck: async (vals: Record<string, string>) => {
      try {
        const n = BigInt(vals.n);
        const phi = BigInt(vals.phi);

        const sum_pq = n - phi + 1n;
        const discriminant = sum_pq * sum_pq - 4n * n;

        if (discriminant < 0n) {
          return `phi(n) is inconsistent with n.\nDiscriminant is negative: ${discriminant}`;
        }

        const sqrt_disc = isqrt(discriminant);
        if (sqrt_disc * sqrt_disc !== discriminant) {
          return null;
        }

        const p = (sum_pq - sqrt_disc) / 2n;
        const q = (sum_pq + sqrt_disc) / 2n;

        if (p * q !== n) {
          return null;
        }

        const phi_check = (p - 1n) * (q - 1n);

        return [
          `Phi(n) Leak Attack (browser-side, BigInt)`,
          `n = ${n}`,
          `phi(n) = ${phi}`,
          `p + q = ${sum_pq}`,
          `Discriminant = ${discriminant}`,
          ``,
          `Factors recovered:`,
          `p = ${p}`,
          `q = ${q}`,
          `Verification: p * q = ${p * q}`,
          `Verification: (p-1)*(q-1) = ${phi_check}`,
          `phi(n) matches: ${phi_check === phi ? 'YES' : 'NO'}`,
        ].join('\n');
      } catch {
        return null;
      }
    },
    proof: `\\textbf{Theorem:} Knowing \\(\\phi(n)\\) for \\(n = pq\\) allows factoring \\(n\\) in polynomial time by solving a quadratic equation.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Modulus \\(n = pq\\) (product of exactly two primes)
\\item Euler's totient \\(\\phi(n) = (p-1)(q-1)\\)
\\item \\(\\Delta = (n - \\phi(n) + 1)^2 - 4n\\) must be a perfect square
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
\\phi(n) &= (p-1)(q-1) = n - (p + q) + 1 \\\\
s &= p + q = n - \\phi(n) + 1 \\\\
\\Delta &= s^2 - 4n = (p - q)^2 \\\\
p &= \\frac{s - \\sqrt{\\Delta}}{2}, \\quad q = \\frac{s + \\sqrt{\\Delta}}{2} \\qed
\\end{align*}

\\textbf{Explanation:} From $n$ and $\\phi(n)$, we derive the sum $s = p + q$. Together with $pq = n$, this gives a quadratic whose roots are $p$ and $q$. The discriminant is always a perfect square $(p-q)^2$ for valid RSA moduli.

\\textbf{References:} Rivest, Shamir, Adleman, 1978; Menezes et al., "Handbook of Applied Cryptography", Section 8.2.2`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.phi),
  },
  {
    id: 'parity-oracle',
    name: 'Parity Oracle Attack',
    description: 'Recovers plaintext bit-by-bit using an oracle that reveals parity of decrypted message.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '65537', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
      { name: 'oracle_responses', label: 'Oracle responses (comma-separated, LSB of each query)', placeholder: '1,0,1,1,0,...', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '65537'})
c = Integer(${vals.c})
responses_str = "${vals.oracle_responses || ''}".replace(' ', '')
responses = [int(x) for x in responses_str.split(',') if x]

print("Parity oracle attack on RSA")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
print(f"Oracle responses: {len(responses)} bits")
print()

n_bits = n.nbits()
if len(responses) < n_bits:
    print(f"WARNING: Need {n_bits} responses for {n_bits}-bit modulus.")
    print(f"Got {len(responses)}. Attack may be incomplete.")
    print()

# Binary search using parity oracle
lower = Integer(0)
upper = Integer(n)

print("Binary search iterations:")
for i, parity in enumerate(responses):
    mid = (lower + upper) // 2

    # Multiply ciphertext by 2^e mod n
    c = (c * power_mod(2, e, n)) % n

    if parity == 0:
        # 2m mod n is even, so 2m < n, m is in lower half
        upper = mid
    else:
        # 2m mod n is odd (since n is odd), so 2m >= n, m is in upper half
        lower = mid

    if i < 10 or i % 50 == 0:
        print(f"  Step {i+1}: parity={parity}, range bits = {(upper - lower).nbits()}")

print()
print(f"Estimated m in range [{lower}, {upper}]")
print(f"Range size: {upper - lower}")

if upper - lower < 10:
    orig_c = Integer(${vals.c})
    for candidate in range(int(lower), int(upper) + 1):
        m = Integer(candidate)
        if power_mod(m, e, n) == orig_c:
            print(f"FOUND! m = {m}")
            try:
                m_bytes = bytes.fromhex(hex(m)[2:] if len(hex(m)) % 2 == 0 else '0' + hex(m)[2:])
                print(f"m as text: {m_bytes.decode('utf-8', errors='replace')}")
            except:
                print(f"m as hex: {hex(m)}")
            break
    else:
        print("Verification failed. Oracle responses may be inconsistent.")
else:
    print(f"Range too large. Need more oracle responses.")
    print(f"Current uncertainty: {(upper - lower).nbits()} bits")
`,
    proof: `\\textbf{Theorem:} A parity oracle returning \\(\\text{LSB}(m)\\) for \\(m = c^d \\bmod n\\) reveals the full plaintext in \\(\\lceil \\log_2 n \\rceil\\) queries.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Public key \\((n, e)\\) and ciphertext \\(c\\)
\\item Oracle \\(\\mathcal{O}(c') = \\text{LSB}((c')^d \\bmod n)\\)
\\item \\(\\lceil \\log_2 n \\rceil\\) oracle queries needed for exact recovery
\\item \\(n\\) must be odd (always true for RSA moduli)
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
c_0 &= c, \\quad m_0 = m \\\\
c_{i+1} &= c_i \\cdot 2^e \\bmod n \\\\
m_{i+1} &= 2 \\cdot m_i \\bmod n \\\\
\\mathcal{O}(c_{i+1}) = 0 &\\implies 2m_i < n \\implies m \\in [\\ell_i, \\tfrac{\\ell_i + u_i}{2}) \\\\
\\mathcal{O}(c_{i+1}) = 1 &\\implies 2m_i \\geq n \\implies m \\in [\\tfrac{\\ell_i + u_i}{2}, u_i) \\\\
\\text{After } k \\text{ steps:} &\\quad u_k - \\ell_k = \\frac{n}{2^k} \\\\
k = \\lceil \\log_2 n \\rceil &\\implies u_k - \\ell_k < 1 \\implies m = \\ell_k \\qed
\\end{align*}

\\textbf{Explanation:} Each query doubles the effective plaintext modulo \\(n\\). The parity of the result reveals whether the doubling wrapped around \\(n\\), halving the search interval. After \\(\\log_2 n\\) steps the interval contains exactly one integer — the plaintext.

\\textbf{References:} D. Bleichenbacher, "Generating ElGamal Signatures Without Knowing the Secret Key", Eurocrypt 1998; Manger, "A Chosen Ciphertext Attack on RSA Optimal Asymmetric Encryption Padding (OAEP)", CRYPTO 2001`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.e && p.c && p.oracle_responses),
  },
];
