import type { Attack } from '../../types';

export const advancedAttacks: Attack[] = [
  {
    id: 'roca',
    name: 'ROCA Vulnerability',
    description: 'Exploits primes generated by Infineon\'s ROCA-vulnerable key generation (p = k·M + (65537^i mod M)).',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})

# ROCA: Return of Coppersmith's Attack
# Primes of form p = k*M + (65537^i mod M)
# M = product of first several primes

print("ROCA vulnerability check")
print(f"n = {n}")
print()

# Try small M values (M_3, M_5, M_7, ...)
primes_list = [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]

found = False
for num_primes in range(1, len(primes_list) + 1):
    M = prod(primes_list[:num_primes])
    if M > 2^32:
        break
    
    # Compute possible remainders: 65537^i mod M
    order = M
    remainders = set()
    a = 1
    for _ in range(order):
        a = (a * 65537) % M
        remainders.add(a)
        if a == 1:
            break
    
    # Check if n mod M is product of two remainders
    n_mod = n % M
    for r1 in remainders:
        if n_mod * inverse_mod(r1, M) % M in remainders:
            print(f"Possible match with M = product of first {num_primes} primes")
            print(f"M = {M}")
            print(f"n mod M = {n_mod}")
            print(f"Found compatible remainders: r1 = {r1}")
            found = True
            break
    if found:
        break

if found:
    print()
    print("VULNERABLE: n appears to use ROCA-generated primes.")
    print("Use Coppersmith's method to recover p.")
    print()
    
    # Coppersmith's method for small M
    # p = k*M + r, where r is known remainder
    # We search for k using Coppersmith
    from sage.libs.ntl import ntl_ZZ_pX, ntl_ZZ_p
    
    r = r1
    R.<x> = PolynomialRing(ZZ)
    f = M*x + r
    
    # Try to find small root
    # p <= sqrt(n), so k <= sqrt(n)/M
    bound = ceil(sqrt(n) / M)
    print(f"Searching for k with bound ~{bound}")
    
    # Use Sage's small_roots
    f_mod = f.change_ring(Zmod(n))
    roots = f_mod.small_roots(X=bound, beta=0.1, epsilon=0.05)
    
    if roots:
        k = int(roots[0])
        p = int(M * k + r)
        if n % p == 0:
            q = n // p
            print(f"SUCCESS! Factor found:")
            print(f"p = {p}")
            print(f"q = {q}")
            print(f"Verification: p * q = {p * q}")
        else:
            print("Root found but does not divide n. Try different parameters.")
    else:
        print("No small root found. n may use a larger M value.")
        print("Try using the full ROCA implementation with larger prime bases.")
else:
    print("n does NOT appear to be ROCA-vulnerable for small M values.")
    print("The primes were likely not generated by Infineon's library.")
`,
    proof: `\\textbf{Theorem: (Nemec et al., 2017)} The ROCA vulnerability affects RSA keys generated by Infineon's cryptographic library (versions 1.01.006–1.02.008 for software, 1.01.001–1.01.007 for hardware). Primes are generated in the form:

\\begin{equation*}
p = k \\cdot M + (65537^{i} \\bmod M)
\\end{equation*}

where $M = \\prod_{j=1}^{m} p_j$ is the product of the first $m$ primes, and $i$ is a random index.

\\textbf{Attack Strategy:}
\\begin{enumerate}
\\item Compute $M$ for various values of $m$ (typically $m \\in \\{3, 5, 7, \\ldots\\}$).
\\item Compute the set of possible remainders $\\mathcal{R} = \\{65537^i \\bmod M : i \\geq 0\\}$.
\\item Check if $n \\bmod M = r_1 \\cdot r_2$ for some $r_1, r_2 \\in \\mathcal{R}$.
\\item If a match is found, use Coppersmith's method to recover $p = k \\cdot M + r_1$.
\\item The polynomial $f(x) = M \\cdot x + r_1$ has a small root $x = k$ modulo $p$.
\\item Coppersmith's method finds roots $x < p^{1/\\delta} / M^{1/\\delta}$ where $\\delta = \\deg(f) = 1$.
\\end{enumerate}

\\textbf{Complexity:} The attack runs in $O(2^{m/2})$ for the fingerprint test and polynomial time for Coppersmith's method once $M$ is identified.

\\textbf{References:} M. Nemec et al., "The Return of Coppersmith's Attack: Practical Factorization of Widely Used RSA Moduli", CCS 2017; https://crocs.fi.muni.cz/roca`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'nitros',
    name: 'Nitros / ROCA Variant',
    description: 'Extended ROCA attack with multiple prime forms and generalized remainders.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'base', label: 'Base (default 65537)', placeholder: '65537', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
base = Integer(${vals.base || '65537'})

print("Nitros / Extended ROCA attack")
print(f"n = {n}")
print(f"base = {base}")
print()

# Try multiple prime bases for M
prime_sets = [
    [3, 5, 7, 11, 13, 17, 19, 23],
    [3, 5, 7, 11, 13, 17, 19, 23, 29, 31],
    [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41],
]

found = False
for primes_subset in prime_sets:
    M = prod(primes_subset)
    
    # Compute remainders
    remainders = set()
    a = 1
    for _ in range(M):
        a = (a * base) % M
        remainders.add(a)
        if a == 1:
            break
    
    n_mod = n % M
    
    # Check if n_mod factors into two remainders
    for r1 in remainders:
        r2 = n_mod * inverse_mod(r1, M) % M
        if r2 in remainders:
            print(f"Match found with M = {M}")
            print(f"r1 = {r1}, r2 = {r2}")
            found = True
            
            # Try Coppersmith
            R.<x> = PolynomialRing(ZZ)
            f = M*x + r1
            bound = ceil(sqrt(n) / M)
            
            f_mod = f.change_ring(Zmod(n))
            roots = f_mod.small_roots(X=bound, beta=0.1, epsilon=0.05)
            
            if roots:
                k = int(roots[0])
                p = int(M * k + r1)
                if n % p == 0:
                    q = n // p
                    print(f"SUCCESS! p = {p}, q = {q}")
                    print(f"Verification: p * q = {p * q}")
                else:
                    print(f"Root found but doesn't divide n. Trying r2...")
                    f2 = M*x + r2
                    roots2 = f2.change_ring(Zmod(n)).small_roots(X=bound, beta=0.1, epsilon=0.05)
                    if roots2:
                        k2 = int(roots2[0])
                        p2 = int(M * k2 + r2)
                        if n % p2 == 0:
                            print(f"SUCCESS! p = {p2}, q = {n // p2}")
            break
    if found:
        break

if not found:
    print("No ROCA/Nitros pattern detected for tested M values.")
`,
    proof: `\\textbf{Theorem:} The Nitros attack generalizes ROCA to primes of the form:

\\begin{equation*}
p = k \\cdot M + (a^{i} \\bmod M)
\\end{equation*}

where $a$ is an arbitrary base (not necessarily 65537) and $M$ is a product of primes.

\\textbf{Generalization:}
\\begin{itemize}
\\item The attack works for any base $a$ with $\\gcd(a, M) = 1$.
\\item The order of $a$ modulo $M$ determines the size of the remainder set $\\mathcal{R}$.
\\item For $|\\mathcal{R}|$ small, checking $n \\bmod M \\in \\mathcal{R} \\cdot \\mathcal{R}$ is efficient.
\\item Coppersmith's method applies when $M > n^{1/4}$ approximately.
\\end{itemize}

\\textbf{Complexity:} $O(|\\mathcal{R}|)$ for the fingerprint test, polynomial in $\\log n$ for Coppersmith.

\\textbf{References:} Nemec et al., CCS 2017; extended analysis in subsequent ROCA research`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'factordb-lookup',
    name: 'FactorDB Lookup',
    description: 'Checks if n has known factors from precomputed factorization databases.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})

print(f"Checking if n = {n} has known factors")
print()

# Try trial division with small primes first
print("Step 1: Trial division with small primes...")
small_primes = primes(10000)
for p in small_primes:
    if n % p == 0:
        q = n // p
        print(f"Found small factor: p = {p}")
        print(f"q = {q}")
        if is_prime(q):
            print("q is prime. Factorization complete!")
        else:
            print(f"q is composite. Further factorization needed.")
            print(f"q factors: {factor(q)}")
        break
else:
    print("No factors found below 10000.")

# Try ECM
print()
print("Step 2: ECM factorization...")
try:
    factors = ecm.factor(n, max_steps=100)
    if factors and len(factors) > 1:
        print(f"ECM found factors: {factors}")
        flist = list(factors)
        if len(flist) == 2:
            p, q = flist[0][0], flist[1][0]
            print(f"p = {p}")
            print(f"q = {q}")
        else:
            print(f"Complete factorization: {factors}")
    else:
        print("ECM did not find factors within step limit.")
except:
    print("ECM failed.")

# Try Pollard's rho
print()
print("Step 3: Pollard's rho...")
try:
    f = pollard_rho(n)
    if f and f != n:
        print(f"Pollard's rho found: {f}")
        print(f"Other factor: {n // f}")
    else:
        print("Pollard's rho did not find a factor.")
except:
    print("Pollard's rho failed.")

print()
print("If n is a known CTF challenge modulus, check:")
print("  - https://factordb.com")
print("  - https://github.com/RsaCtfTool/RsaCtfTool")
print("  - Common CTF challenge databases")
`,
    proof: `\\textbf{Theorem:} Many RSA moduli used in CTF challenges and real-world deployments have been pre-factored and stored in public databases.

\\textbf{FactorDB:} The website factordb.com maintains a database of known factorizations. When querying a modulus $n$:
\\begin{enumerate}
\\item If $n$ has been previously factored, the database returns the prime factors immediately.
\\item If $n$ is new, the database may factor it using distributed computation.
\\end{enumerate}

\\textbf{Why this works:}
\\begin{itemize}
\\item CTF challenges often reuse or generate weak moduli.
\\item Many real-world RSA keys share factors due to poor randomness.
\\item Large-scale factorization projects (e.g., NFS on RSA challenge numbers) publish results.
\\end{itemize}

\\textbf{Practical approach:}
\\begin{enumerate}
\\item Trial division with primes up to $10^6$.
\\item ECM with increasing curve bounds.
\\item Pollard's rho for medium factors.
\\item Query FactorDB API for precomputed results.
\\end{enumerate}

\\textbf{References:} https://factordb.com; RsaCtfTool project`,
    priority: 'low',
    applicableCheck: (p: Record<string, string>) => !!p.n,
  },
  {
    id: 'known-plaintext',
    name: 'Known Plaintext Attack',
    description: 'Recovers RSA parameters when the plaintext structure is partially known.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '65537', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
      { name: 'known_prefix', label: 'Known plaintext prefix (optional)', placeholder: 'e.g., flag{', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '65537'})
c = Integer(${vals.c})
known_prefix = "${vals.known_prefix || ''}"

print("Known plaintext attack on RSA")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
if known_prefix:
    print(f"Known prefix: '{known_prefix}'")
print()

# Convert known prefix to integer
if known_prefix:
    prefix_bytes = known_prefix.encode('utf-8')
    prefix_int = Integer(int.from_bytes(prefix_bytes, 'big'))
    prefix_len = len(prefix_bytes)
    
    print(f"Prefix as integer: {prefix_int}")
    print(f"Prefix byte length: {prefix_len}")
    print()
    
    # The plaintext m has form: m = prefix_int * 256^k + unknown
    # where k is the number of unknown bytes
    # c = m^e mod n
    # We need to find m such that m^e = c (mod n) and m starts with prefix
    
    # Estimate total message length
    n_bits = n.nbits()
    max_bytes = n_bits // 8
    
    # Try brute force for small unknown portions
    unknown_bytes = max_bytes - prefix_len
    print(f"Estimated message length: {max_bytes} bytes")
    print(f"Unknown portion: {unknown_bytes} bytes")
    print()
    
    if unknown_bytes <= 4:
        print(f"Brute forcing {unknown_bytes} unknown byte(s)...")
        bound = 256^unknown_bytes
        for k in range(bound):
            m = prefix_int * (256^unknown_bytes) + k
            if power_mod(m, e, n) == c:
                print(f"FOUND! m = {m}")
                print(f"m as bytes: {bytes.fromhex(hex(m)[2:])}")
                break
        else:
            print("Brute force exhausted without finding match.")
    elif unknown_bytes <= 10:
        print(f"Using Coppersmith's method for {unknown_bytes} unknown bytes...")
        # m = prefix * 2^k + x, where x is small
        R.<x> = PolynomialRing(Zmod(n))
        shift = 256^unknown_bytes
        f = (prefix_int * shift + x)^e - c
        roots = f.small_roots(X=shift, beta=1.0, epsilon=0.01)
        if roots:
            x = int(roots[0])
            m = prefix_int * shift + x
            print(f"FOUND! m = {m}")
            try:
                print(f"m as bytes: {bytes.fromhex(hex(m)[2:].zfill(max_bytes*2))}")
            except:
                print(f"m as hex: {hex(m)}")
        else:
            print("Coppersmith's method did not find a solution.")
            print("Try increasing epsilon or the unknown portion may be too large.")
    else:
        print(f"Unknown portion ({unknown_bytes} bytes) too large for direct attack.")
        print("Consider: lattice attacks, partial key recovery, or other methods.")
else:
    print("No known prefix provided.")
    print("Try: small e attack, common modulus attack, or factorization methods.")
`,
    proof: `\\textbf{Theorem:} When partial knowledge of the plaintext $m$ is available, RSA can be broken using Coppersmith's method.

\\textbf{Setup:} Suppose $m = m_0 \\cdot 2^k + x$, where $m_0$ is the known prefix and $x < 2^k$ is unknown.

\\textbf{Coppersmith's Method:}
\\begin{enumerate}
\\item Construct $f(x) = (m_0 \\cdot 2^k + x)^e - c \\pmod{n}$.
\\item We seek a root $x_0$ with $|x_0| < X = 2^k$.
\\item Coppersmith finds small roots when $X < n^{1/e}$ (for monic polynomials).
\\item For RSA with $e = 65537$, this allows recovering up to $\\approx \\frac{1}{e}$ fraction of the message.
\\item For small $e$ (e.g., $e = 3$), up to $\\approx 1/3$ of the message can be unknown.
\\end{enumerate}

\\textbf{Brute Force:} When the unknown portion is $\\leq 4$ bytes, exhaustive search is practical.

\\textbf{References:} D. Coppersmith, "Small Solutions to Polynomial Equations", 1997; May, "New RSA Vulnerabilities Using Lattice Reduction Methods", 2003`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.c),
  },
  {
    id: 'small-public-exp',
    name: 'Small Public Exponent Analysis',
    description: 'Detects and exploits very small public exponent values (e = 3, 5, 17).',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '3', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '3'})
c = Integer(${vals.c})

print(f"Small public exponent analysis")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
print()

# Check if e is small
if e >= 100:
    print(f"e = {e} is not considered 'small' for this attack.")
    print("This attack is effective for e in {3, 5, 17}.")
    print("Try other attack methods.")
else:
    print(f"e = {e} is small. Checking for vulnerabilities...")
    print()
    
    # Attack 1: e-th root (m^e < n)
    print("Attack 1: e-th root attack (m^e < n)")
    m_root = c.nth_root(e, truncate_mode='floor')
    if m_root^e == c:
        print(f"SUCCESS! c is a perfect {e}-th power.")
        print(f"m = {m_root}")
        try:
            m_bytes = bytes.fromhex(hex(m_root)[2:].zfill(2))
            print(f"m as text: {m_bytes.decode('utf-8', errors='replace')}")
        except:
            print(f"m as hex: {hex(m_root)}")
    else:
        print(f"c is not a perfect {e}-th power over integers.")
        print("m^e >= n, so modular reduction occurred.")
    print()
    
    # Attack 2: Hastad broadcast (need multiple (n, c) pairs)
    print("Attack 2: Hastad broadcast note")
    print("If the SAME message m was encrypted with e = 3")
    print("under 3 DIFFERENT moduli n1, n2, n3, then:")
    print("  m = CRT(c1, c2, c3)^(1/3) over integers")
    print("Provide additional (n, c) pairs to attempt this attack.")
    print()
    
    # Attack 3: Franklin-Reiter related message
    print("Attack 3: Franklin-Reiter related message note")
    print("If two ciphertexts c1 = m^e and c2 = (m + delta)^e")
    print("are known with the same (n, e), then m can be recovered.")
    print("Provide a second ciphertext to attempt this attack.")
`,
    proof: `\\textbf{Theorem:} RSA with small public exponent $e \\in \\{3, 5, 17\\}$ is vulnerable to several attacks.

\\textbf{Attack 1: e-th Root (no padding)}
If $m^e < n$, then $c = m^e$ (no modular reduction), and $m = \\sqrt[e]{c}$ over $\\mathbb{Z}$.
This occurs when $m < n^{1/e}$. For $e = 3$ and 2048-bit $n$, this means $m < 2^{683}$.

\\textbf{Attack 2: Hastad Broadcast}
If the same message $m$ is encrypted under $e$ different moduli $n_1, \\ldots, n_e$:
\\begin{equation*}
c_i = m^e \\pmod{n_i} \\quad \\text{for } i = 1, \\ldots, e
\\end{equation*}
Then by CRT, $m^e \\bmod N = c$ where $N = \\prod n_i$, and since $m^e < N$, we recover $m = \\sqrt[e]{c}$.

\\textbf{Attack 3: Franklin-Reiter Related Message}
If $c_1 = m^e \\bmod n$ and $c_2 = (am + b)^e \\bmod n$ are known, then $m$ can be recovered in $O(e^2 \\log^2 n)$ time by computing $\\gcd(x^e - c_1, (ax + b)^e - c_2)$ over $\\mathbb{Z}_n$.

\\textbf{Mitigation:} Always use proper padding (OAEP) to ensure $m$ is randomized and $m^e \\geq n$.

\\textbf{References:} Hastad, "Solving linear equations by means of lattice reductions", 1988; Franklin & Reiter, "The relation between short exponents and related-message attacks", 1996`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.e && p.c),
  },
  {
    id: 'multi-prime-gcd',
    name: 'Multi-Prime GCD',
    description: 'Finds shared prime factors across multiple RSA moduli (batch GCD attack).',
    category: 'Advanced',
    inputs: [
      { name: 'moduli_list', label: 'Moduli (one per line)', placeholder: 'Enter multiple moduli, one per line...', multiline: true, rows: 6 },
    ],
    sageTemplate: (vals: Record<string, string>) => `# Parse moduli
moduli_str = """${vals.moduli_list}""".strip()
moduli = [Integer(x.strip()) for x in moduli_str.split('\\n') if x.strip()]

print(f"Multi-Prime GCD attack on {len(moduli)} moduli")
print()

if len(moduli) < 2:
    print("Need at least 2 moduli for this attack.")
else:
    # Batch GCD: compute product of all moduli, then GCD each with product/others
    print("Computing batch GCD...")
    print()
    
    found_any = False
    for i in range(len(moduli)):
        ni = moduli[i]
        for j in range(i + 1, len(moduli)):
            nj = moduli[j]
            g = gcd(ni, nj)
            if g > 1 and g < ni:
                found_any = True
                print(f"SHARED FACTOR FOUND between moduli {i+1} and {j+1}!")
                print(f"gcd(n{i+1}, n{j+1}) = {g}")
                print(f"n{i+1} = {ni}")
                print(f"  p = {g}")
                print(f"  q = {ni // g}")
                print(f"n{j+1} = {nj}")
                print(f"  p' = {g}")
                print(f"  q' = {nj // g}")
                print()
    
    if not found_any:
        print("No shared factors found among the provided moduli.")
        print()
        print("This could mean:")
        print("  1. All moduli use independently generated primes (good practice)")
        print("  2. The shared factors are not between the provided pairs")
        print("  3. More moduli are needed to find common factors")
        print()
        print("Note: In real-world scans, ~0.2% of RSA certificates share factors")
        print("due to poor entropy during key generation.")
`,
    proof: `\\textbf{Theorem: (Heninger et al., 2012)} When RSA moduli are generated with insufficient entropy, different moduli may share prime factors.

\\textbf{Batch GCD Attack:}
Given $k$ moduli $n_1, n_2, \\ldots, n_k$, compute:
\\begin{equation*}
g_{ij} = \\gcd(n_i, n_j) \\quad \\text{for all } 1 \\leq i < j \\leq k
\\end{equation*}

If $g_{ij} > 1$, then $n_i$ and $n_j$ share a prime factor, and both are immediately factored:
\\begin{equation*}
n_i = g_{ij} \\cdot \\frac{n_i}{g_{ij}}, \\quad n_j = g_{ij} \\cdot \\frac{n{n_j}}{g_{ij}}
\\end{equation*}

\\textbf{Efficient Implementation:}
\\begin{enumerate}
\\item Compute $P = \\prod_{i=1}^k n_i$.
\\item For each $i$, compute $g_i = \\gcd(n_i, P / n_i^2)$.
\\item If $g_i > 1$, then $n_i$ shares a factor with some $n_j$.
\\item This reduces complexity from $O(k^2)$ GCDs to $O(k)$ GCDs.
\\end{enumerate}

\\textbf{Real-World Impact:} In a 2012 study, 0.2\\% of TLS certificates had shared factors due to embedded devices with poor RNGs.

\\textbf{References:} N. Heninger et al., "Mining Your Ps and Qs: Detection of Widespread Weak Keys in Network Devices", USENIX Security 2012`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!(p.moduli_list && p.moduli_list.trim().split('\\n').filter(x => x.trim()).length >= 2),
  },
  {
    id: 'phi-leak',
    name: 'Phi(n) Leak',
    description: 'Recovers prime factors when Euler\'s totient function phi(n) is leaked.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'phi', label: 'phi(n) (Euler totient)', placeholder: 'Enter phi(n)...', multiline: true, rows: 3 },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
phi = Integer(${vals.phi})

print("Phi(n) leak attack")
print(f"n = {n}")
print(f"phi(n) = {phi}")
print()

# For n = p*q: phi(n) = (p-1)(q-1) = pq - p - q + 1 = n - p - q + 1
# So: p + q = n - phi + 1
# And: p * q = n
# We solve: x^2 - (p+q)x + pq = 0
# i.e.: x^2 - (n - phi + 1)x + n = 0

sum_pq = n - phi + 1
print(f"p + q = {sum_pq}")
print(f"p * q = {n}")
print()

# Solve quadratic: x^2 - sum_pq * x + n = 0
discriminant = sum_pq^2 - 4*n
print(f"Discriminant = {discriminant}")

if discriminant < 0:
    print("ERROR: Negative discriminant. phi(n) is inconsistent with n.")
elif discriminant == 0:
    print("ERROR: p = q. n is a perfect square (not valid RSA).")
else:
    sqrt_disc = isqrt(discriminant)
    if sqrt_disc^2 == discriminant:
        p = (sum_pq - sqrt_disc) // 2
        q = (sum_pq + sqrt_disc) // 2
        print(f"SUCCESS! Factors recovered:")
        print(f"p = {p}")
        print(f"q = {q}")
        print(f"Verification: p * q = {p * q}")
        print(f"Verification: (p-1)*(q-1) = {(p-1)*(q-1)}")

        try:
            e_val = Integer(${vals.e || '0'})
            if e_val > 0:
                d = inverse_mod(e_val, phi)
                print(f"d (private exponent) = {d}")
        except:
            pass
    else:
        print(f"Discriminant is not a perfect square: {discriminant}")
        print("phi(n) may be incorrect, or n has more than 2 prime factors.")
`,
    proof: `\\textbf{Theorem:} If $n = pq$ and $\\phi(n)$ is known, then $n$ can be factored in polynomial time.

\\textbf{Derivation:}
\\begin{align*}
\\phi(n) &= (p-1)(q-1) = pq - p - q + 1 = n - (p + q) + 1 \\\\
p + q &= n - \\phi(n) + 1 \\\\
pq &= n
\\end{align*}

Given $s = p + q$ and $pq = n$, we solve the quadratic:
\\begin{equation*}
x^2 - sx + n = 0
\\end{equation*}

The discriminant is $\\Delta = s^2 - 4n = (p-q)^2$, so:
\\begin{equation*}
p = \\frac{s - \\sqrt{\\Delta}}{2}, \\quad q = \\frac{s + \\sqrt{\\Delta}}{2}
\\end{equation*}

\\textbf{Complexity:} $O(\\log^2 n)$ for the arithmetic operations.

\\textbf{Implication:} Knowing $\\phi(n)$ is equivalent to factoring $n$. This is why $\\phi(n)$ must be kept secret in RSA.

\\textbf{References:} RSA original paper (Rivest, Shamir, Adleman, 1978); Menezes et al., "Handbook of Applied Cryptography", Section 8.2.2`,
    priority: 'high',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.phi),
  },
  {
    id: 'parity-oracle',
    name: 'Parity Oracle Attack',
    description: 'Recovers plaintext bit-by-bit using an oracle that reveals parity of decrypted message.',
    category: 'Advanced',
    inputs: [
      { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
      { name: 'e', label: 'e (public exponent)', placeholder: '65537', multiline: false },
      { name: 'c', label: 'c (ciphertext)', placeholder: 'Enter ciphertext c...', multiline: true, rows: 3 },
      { name: 'oracle_responses', label: 'Oracle responses (comma-separated, LSB of each query)', placeholder: '1,0,1,1,0,...', multiline: false },
    ],
    sageTemplate: (vals: Record<string, string>) => `n = Integer(${vals.n})
e = Integer(${vals.e || '65537'})
c = Integer(${vals.c})
responses_str = "${vals.oracle_responses || ''}".replace(' ', '')
responses = [int(x) for x in responses_str.split(',') if x]

print("Parity oracle attack on RSA")
print(f"n = {n}")
print(f"e = {e}")
print(f"c = {c}")
print(f"Oracle responses: {len(responses)} bits")
print()

n_bits = n.nbits()
if len(responses) < n_bits:
    print(f"WARNING: Need {n_bits} responses for {n_bits}-bit modulus.")
    print(f"Got {len(responses)}. Attack may be incomplete.")
    print()

# Binary search using parity oracle
lower = Integer(0)
upper = Integer(n)

print("Binary search iterations:")
for i, parity in enumerate(responses):
    mid = (lower + upper) // 2

    # Multiply ciphertext by 2^e mod n
    c = (c * power_mod(2, e, n)) % n

    if parity == 0:
        # 2m mod n >= n, so m is in upper half
        lower = mid
    else:
        # 2m mod n < n, so m is in lower half
        upper = mid

    if i < 10 or i % 50 == 0:
        print(f"  Step {i+1}: parity={parity}, range bits = {(upper - lower).nbits()}")

print()
print(f"Estimated m in range [{lower}, {upper}]")
print(f"Range size: {upper - lower}")

if upper - lower < 10:
    orig_c = Integer(${vals.c})
    for candidate in range(int(lower), int(upper) + 1):
        m = Integer(candidate)
        if power_mod(m, e, n) == orig_c:
            print(f"FOUND! m = {m}")
            try:
                m_bytes = bytes.fromhex(hex(m)[2:].zfill(2))
                print(f"m as text: {m_bytes.decode('utf-8', errors='replace')}")
            except:
                print(f"m as hex: {hex(m)}")
            break
    else:
        print("Verification failed. Oracle responses may be inconsistent.")
else:
    print(f"Range too large. Need more oracle responses.")
    print(f"Current uncertainty: {(upper - lower).nbits()} bits")
`,
    proof: `\\textbf{Theorem: (Bleichenbacher, 1998)} Given access to a parity oracle that returns the least significant bit of $m = c^d \\bmod n$, the full plaintext $m$ can be recovered in $\\log_2 n$ queries.

\\textbf{Key Insight:} Multiplying the ciphertext by $2^e \\bmod n$ corresponds to doubling the plaintext modulo $n$:
\\begin{equation*}
(c \\cdot 2^e)^d \\equiv m \\cdot 2 \\pmod{n}
\\end{equation*}

\\textbf{Binary Search:}
\\begin{enumerate}
\\item If $2m < n$, the parity oracle returns $2m \\bmod 2 = 0$ (even).
\\item If $2m \\geq n$, the parity oracle returns $(2m - n) \\bmod 2 = 1$ (since $n$ is odd).
\\item Each query halves the search interval for $m$.
\\item After $\\log_2 n$ queries, $m$ is determined exactly.
\\end{enumerate}

\\textbf{Interval refinement:}
\\begin{itemize}
\\item Start with $m \\in [0, n)$.
\\item If parity is 0: $m \\in [0, n/2)$.
\\item If parity is 1: $m \\in [n/2, n)$.
\\item After each step, multiply $c$ by $2^e$ and repeat.
\\end{itemize}

\\textbf{Complexity:} $O(\\log n)$ oracle queries, each taking $O(\\log^3 n)$ time.

\\textbf{References:} D. Bleichenbacher, "Generating ElGamal Signatures Without Knowing the Secret Key", Eurocrypt 1998; Manger, "A Chosen Ciphertext Attack on RSA Optimal Asymmetric Encryption Padding (OAEP)", CRYPTO 2001`,
    priority: 'medium',
    applicableCheck: (p: Record<string, string>) => !!(p.n && p.e && p.c && p.oracle_responses),
  },
];
