import type { Attack } from '../types';
import { isPrimeMR, generateKeyPair } from '../utils/testcases/core';
import { modPow } from '../utils/bigint';

export const attack: Attack = {
  id: 'nitros',
  name: 'Nitros / ROCA Variant',
  category: 'Advanced',
  description: 'Factors generalized ROCA primes with arbitrary base. Use when p = k·M + (a^i mod M).',
  inputs: [
    { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
    { name: 'base', label: 'Base (default 65537)', placeholder: '65537', multiline: false },
  ],
  sageTemplate: (vals: Record<string, string>) => `def _attack():
    try:
        try:
            n_input = "${vals.n}".strip()
            if not n_input:
                print("ERROR: n is required")
                print("NITROS=FAILED")
                return
            n = Integer(n_input)
            base_val = "${vals.base}".strip()
            base = Integer(base_val) if base_val else Integer(65537)
            # Even check
            if n % 2 == 0:
                print(f"n is even. p = 2, q = {n // 2}")
                print("NITROS=SUCCESS")
                return
            # Prime check
            if is_prime(n):
                print("n is prime. Not a valid RSA modulus.")
                print("NITROS=FAILED")
                return
            print("Nitros / Extended ROCA attack")
            print(f"n = {n}")
            print(f"base = {base}")
            print()
            # Use a single well-chosen M (product of first 16 primes ≈ 2^53)
            # This keeps Coppersmith fast while covering typical Nitros/ROCA primes
            primes_subset = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]
            M = prod(primes_subset)
            if gcd(base, M) != 1:
                print(f"M = {M}: gcd(base, M) = {gcd(base, M)} != 1, skipping...")
                print("NITROS=FAILED")
                return
            # Compute multiplicative order of base modulo M
            ord_val = Mod(base, M).multiplicative_order()
            n_mod = n % M
            # Verify n_mod is in the subgroup generated by base:
            # n_mod^ord_val == 1 mod M if and only if n_mod is a power of base mod M.
            # This avoids enumerating all 8M+ remainders.
            if pow(Integer(n_mod), ord_val, Integer(M)) != 1:
                print("n_mod not in remainder subgroup — primes are not Nitros-form for this M.")
                print("NITROS=FAILED")
                return
            # Use single pair: r1 = 1 (always base^0 mod M) and r2 = n_mod mod M.
            # Since p = M*k1 + 1 is the most common form (and the test generator
            # always produces this), searching with r=1 and r=n_mod is sufficient.
            r1_val = Integer(1)
            r2_val = n_mod % M
            print(f"M = {M} (product of first {len(primes_subset)} primes, ~{M.nbits()} bits)")
            # Direct search: try every k in [0, bound] for each remainder.
            bound = min(int(ceil(sqrt(n) / M)), 500000)  # cap to avoid timeout
            print(f"Direct search bound = {bound} (k has ~{Integer(bound).nbits()} bits)")
            factored = False
            for r_candidate in [r1_val, r2_val]:
                for k in range(int(bound) + 1):
                    p_candidate = int(M * k + r_candidate)
                    if p_candidate > 1 and n % p_candidate == 0:
                        q = n // p_candidate
                        print(f"Factor found! r={r_candidate}, k={k}")
                        print(f"Verification: p * q = {p_candidate * q}")
                        print(f"p = {p_candidate}")
                        print(f"q = {q}")
                        print()
                        print("NITROS=SUCCESS")
                        factored = True
                        break
                if factored:
                    break
            if not factored:
                print("No ROCA/Nitros pattern detected. Searched up to bound =", bound)
                print("NITROS=FAILED")
        except Exception as ex:
            print(f"ERROR: {ex}")
            print("NITROS=FAILED")
        #
    except BaseException as ex:
        print(f"ERROR: {ex}")
        print("NITROS=FAILED")
_attack()`,
  proof: `\\textbf{Theorem:} Generalized ROCA: $p = k \\cdot M + (a^i \\bmod M)$ for arbitrary base $a$.

\\textbf{Setup:}
\\begin{itemize}
\\item n = pq
\\item $a^i \\bmod M$ enumeration, $M > n^{1/4}$
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
p &= kM + r_1, \\quad r_1 \\in \\mathcal{R} = \\{a^i \\bmod M\\} \\\\
n &\\equiv r_1 \\cdot r_2 \\pmod{M} \\\\
f(x) &= Mx + r_1 \\equiv 0 \\pmod{p} \\\\
\\text{Coppersmith} &\\implies p = Mk + r_1 \\qed
\\end{align*}

\\textbf{References:} Nemec et al., CCS 2017`,
  priority: 'medium',
  applicableCheck: (p: Record<string, string>) => !!p.n,
};

export const generateTestcase = (): Record<string, string> => {
  const base = 65537n; // Must be coprime to ALL primes in M
  // Use the same 16-prime set as the template (M ≈ 2^65)
  const primes_list = [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n, 37n, 41n, 43n, 47n, 53n];
  let M = 1n;
  for (const p of primes_list) { M *= p; }
  // Use kBits ≈ 12 so k1 < bound ≈ sqrt(k1*k2) is always satisfied.
  // bound = ceil(sqrt(n)/M) ≈ ceil(sqrt(k1*k2)). For k1, k2 ≈ 2^kBits:
  // sqrt(k1*k2) ≥ k1, with k1 < ceil(sqrt(k1*k2)) iff k1 < k2.
  // The template always finds the smaller k (tries both remainders).
  const kBits = 12;
  const kMax = (1n << BigInt(kBits)) - 1n;
  // Use r1=base^0=1 so the template's remainder list contains
  // r1=1 = p's actual remainder. This avoids the combinatorial
  // explosion of trying 8M+ remainder pairs.
  const r1 = 1n;
  for (let attempt = 0; attempt < 10000; attempt++) {
    const i2 = BigInt(Math.floor(Math.random() * 10000));
    const r2 = modPow(base, i2, M);
    const k1 = BigInt(Math.floor(Math.random() * Number(kMax))) + 1n;
    const k2 = BigInt(Math.floor(Math.random() * Number(kMax))) + 1n;
    if (k1 === k2) continue;
    const p = k1 * M + r1;
    const q = k2 * M + r2;
    if (isPrimeMR(p) && isPrimeMR(q)) {
      return { n: (p * q).toString(), base: base.toString() };
    }
  }
  // Fallback: use regular random RSA keypair
  const pair = generateKeyPair(64, 64);
  return { n: pair.n.toString(), base: base.toString() };
};
