import type { Attack } from '../types';
import { randomPrime } from '../utils/testcases/core';
import { modPow } from '../utils/bigint';
import { generateKeyPair } from '../utils/testcases/core';

export const attack: Attack = {
  id: 'roca',
  name: 'ROCA Vulnerability',
  category: 'Advanced',
  description: 'Factors ROCA-vulnerable primes. Use when p = k·M + (65537^i mod M).',
  inputs: [
    { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
  ],
  sageTemplate: (vals: Record<string, string>) => `def _attack():
    try:
        # Validate inputs
        try:
            if not "${vals.n}".strip():
                print("ERROR: n is required")
                print("ROCA=FAILED")
                return
            n = Integer(${vals.n})
            # Even check
            if n % 2 == 0:
                print(f"n is even. p = 2, q = {n // 2}")
                print("ROCA=SUCCESS")
                return
            # Prime check
            if is_prime(n):
                print("n is prime. Not a valid RSA modulus.")
                print("ROCA=FAILED")
                return
            # ROCA: Return of Coppersmith's Attack
            # Primes of form p = k*M + (65537^i mod M)
            # M = product of first several primes
            print("ROCA vulnerability check")
            print(f"n = {n}")
            print()
            # Try small M values (M_3, M_5, M_7, ...)
            primes_list = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]
            found = False
            r1 = 0
            for num_primes in range(1, len(primes_list) + 1):
                M = prod(primes_list[:num_primes])
                if M > 2**80:
                    break
                # Compute possible remainders: 65537^i mod M
                ord_val = Mod(65537, M).multiplicative_order()
                remainders = set()
                for idx in range(ord_val):
                    r = power_mod(65537, idx, M)
                    remainders.add(r)
                # Check if n mod M is product of two remainders
                n_mod = n % M
                for r in remainders:
                    if n_mod * inverse_mod(r, M) % M in remainders:
                        print(f"Possible match with M = product of first {num_primes} primes")
                        print(f"M = {M}")
                        print(f"n mod M = {n_mod}")
                        print(f"Found compatible remainders: r1 = {r}")
                        found = True
                        r1 = r
                        break
                if found:
                    break
            if found:
                print()
                print("VULNERABLE: n appears to use ROCA-generated primes.")
                print("Use Coppersmith's method to recover p.")
                print()
                # Coppersmith's method for small M
                # p = k*M + r, where r is known remainder
                # We search for k using Coppersmith
                r = r1
                R.<x> = PolynomialRing(ZZ)
                f = M*x + r
                # Try to find small root
                # p <= sqrt(n), so k <= sqrt(n)/M
                bound = ceil(sqrt(n) / M)
                print(f"Searching for k with bound ~{bound}")
                # Use Sage's small_roots
                f_mod = f.change_ring(Zmod(n))
                roots = f_mod.small_roots(X=bound, beta=0.5, epsilon=0.05)
                if roots:
                    k = int(roots[0])
                    p = int(M * k + r)
                    if n % p == 0:
                        q = n // p
                        print(f"SUCCESS! Factor found:")
                        print(f"p = {p}")
                        print(f"q = {q}")
                        print(f"Verification: p * q = {p * q}")
                        print("ROCA=SUCCESS")
                    else:
                        print("Root found but does not divide n. Try different parameters.")
                        print("ROCA=FAILED")
                else:
                    print("No small root found. n may use a larger M value.")
                    print("Try using the full ROCA implementation with larger prime bases.")
                    print("ROCA=FAILED")
            else:
                print("n does NOT appear to be ROCA-vulnerable for small M values.")
                print("The primes were likely not generated by Infineon's library.")
                print("ROCA=FAILED")
        except Exception as ex:
            print(f"ERROR: {ex}")
            print("ROCA=FAILED")
        #
    except BaseException as ex:
        print(f"ERROR: {ex}")
        print("ROCA=FAILED")
_attack()`,
  proof: `\\textbf{Theorem:} RSA primes generated by Infineon's ROCA-vulnerable library (v1.01.006–v1.02.008) have the form \\(p = k \\cdot M + (65537^{i} \\bmod M)\\), enabling factorization via Coppersmith's method.

\\textbf{Prerequisites:}
\\begin{itemize}
\\item Modulus \\(n = pq\\) where at least one prime was generated by Infineon's library
\\item \\(M = \\prod_{j=1}^{m} p_j\\) — product of first \\(m\\) small primes
\\item The remainder set \\(\\mathcal{R} = \\{65537^i \\bmod M : i \\geq 0\\}\\) must be small enough to enumerate
\\item \\(M > n^{1/4}\\) for Coppersmith's method to succeed
\\end{itemize}

\\textbf{Proof:}
\\begin{align*}
p &= k \\cdot M + r_1, \\quad r_1 \\in \\mathcal{R} \\\\
q &= k' \\cdot M + r_2, \\quad r_2 \\in \\mathcal{R} \\\\
n &= pq \\equiv r_1 \\cdot r_2 \\pmod{M} \\\\
f(x) &= M \\cdot x + r_1 \\equiv 0 \\pmod{p} \\\\
|x_0| = k &< \\frac{\\sqrt{n}}{M} < p^{1/\\delta} \\quad (\\delta = \\deg f = 1) \\\\
\\text{Coppersmith recovers } x_0 = k &\\implies p = M \\cdot k + r_1 \\qed
\\end{align*}

\\textbf{Explanation:} The attack fingerprints \\(n \\bmod M\\) against products of known remainders. A match identifies the correct \\(M\\) and remainder \\(r_1\\), then Coppersmith's method recovers \\(k\\) from the linear polynomial \\(f(x) = Mx + r_1\\) modulo \\(p\\).

\\textbf{References:} M. Nemec et al., "The Return of Coppersmith's Attack: Practical Factorization of Widely Used RSA Moduli", CCS 2017; https://crocs.fi.muni.cz/roca`,
  priority: 'high',
  applicableCheck: (p: Record<string, string>) => !!p.n,
};

export const generateTestcase = (): Record<string, string> => {
  const primes_list = [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n, 37n, 41n, 43n, 47n, 53n, 59n, 61n];
  let M = 1n;
  for (const p of primes_list) { M *= p; }
  // M ≈ 2^77, p should be ~256 bits → k needs ~179 bits
  const kBits = 10;
  for (let attempt = 0; attempt < 5000; attempt++) {
    const i = BigInt(Math.floor(Math.random() * 10000));
    const r = modPow(65537n, i, M);
    // Generate random k of appropriate bit size
    const kBytes = Math.ceil(kBits / 8);
    const bytes = new Uint8Array(kBytes);
    crypto.getRandomValues(bytes);
    let k = 0n;
    for (let j = 0; j < kBytes; j++) { k = (k << 8n) | BigInt(bytes[j]); }
    k |= (1n << BigInt(kBits - 1)); // set top bit
    k |= 1n; // ensure odd
    const p = k * M + r;
    if ((p)) {
      const q = randomPrime(64);
      return { n: (p * q).toString() };
    }
  }
  const pair = generateKeyPair(64, 64);
  return { n: pair.n.toString() };
};
