import type { Attack } from '../types';
import { modPow } from '../utils/bigint';
import { generateKeyPair, isPrimeMR } from '../utils/testcases/core';
import { wrapSageTemplate } from './guard';


export const attack: Attack = {
  id: 'roca',
  name: 'ROCA Vulnerability',
  category: 'Advanced',
  description: 'Factors ROCA-vulnerable (Infineon) RSA keys where p = k·M + (65537^i mod M) via discrete_log detection and Howgrave-Graham Coppersmith. For 512-bit keys SageCell may timeout; use FactorDB or local Sage for full factorization.',
  inputs: [
    { name: 'n', label: 'n (modulus)', placeholder: 'Enter modulus n...', multiline: true, rows: 3 },
  ],
  sageTemplate: (vals: Record<string, string>) => wrapSageTemplate({
    token: 'ROCA',
    n: vals.n,
    useGuard: true,
    body: `        R.<x> = PolynomialRing(ZZ)
        out.append("ROCA Vulnerability")
        out.append("")
        out.append("n = " + str(n))
        out.append("")
        out.append("Results:")
        bits = n.nbits()
        # Full list of primes up to 167 (39 primes)
        primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167]
        # Build M as product of first N primes where M < sqrt(n)
        M = 1
        used = []
        sqrt_n = Integer(isqrt(n))
        for p in primes:
            if M * p >= sqrt_n:
                break
            M *= p
            used.append(p)
        if len(used) < 4:
            out.append("ROCA=FAILED")
        else:

            # Detection: check if n mod M is in the subgroup generated by 65537
            Rm = Zmod(M)
            g = Rm(65537)
            n_mod_M = Rm(n)
            ord_M = g.multiplicative_order()
            # Check if n mod M is in subgroup via discrete_log
            detected = False
            try:
                c = discrete_log(n_mod_M, g)
                detected = True
            except (ValueError, TypeError, ArithmeticError):
                out.append("ROCA=FAILED")
            if detected:
                out.append("ROCA VULNERABILITY DETECTED")
                # Compute max M' dividing M_val where ord_{65537}(M') divides ord_
                def _cmm(M_val, ord_):
                    for pf, pe in factor(M_val):
                        pp = pf ** pe
                        ord_pp = Zmod(pp)(65537).multiplicative_order()
                        if ord_ % ord_pp != 0:
                            M_val //= pp
                    return M_val
                # Greedy M' optimization
                def _gfm(M_val):
                    ord_val = Zmod(M_val)(65537).multiplicative_order()
                    while True:
                        best_r = 0
                        best_ord = ord_val
                        best_M = M_val
                        for of, oe in factor(ord_val):
                            for _pi in range(1, oe + 1):
                                ord_try = ord_val // (of ** _pi)
                                M_try = _cmm(M_val, ord_try)
                                if M_try > 0 and M_try != M_val:
                                    r = (log(ord_val, 2) - log(ord_try, 2)) / (log(M_val, 2) - log(M_try, 2))
                                    if r > best_r:
                                        best_r = r
                                        best_ord = ord_try
                                        best_M = M_try
                        if best_r <= 0 or Integer(best_M).nbits() < bits // 4:
                            break
                        ord_val = best_ord
                        M_val = best_M
                    return M_val, ord_val
                M_prime, ord_prime = _gfm(M)
                g_mod_Mp = Zmod(M_prime)(65537)
                c_prime = discrete_log(Zmod(M_prime)(n), g_mod_Mp)
                X = Integer(2 * isqrt(n) // M_prime)

                if X < 1:
                    out.append("ROCA=FAILED")
                else:
                    # Coppersmith params based on key size
                    if bits <= 960:
                        mm, tt = 5, 6
                    elif bits <= 1952:
                        mm, tt = 4, 5
                    else:
                        mm, tt = 7, 8
                    # Howgrave-Graham Coppersmith for univariate modular polynomial
                    def _chu(pol, modulus, beta, mm, tt, XX):
                        dd = pol.degree()
                        nn = dd * mm + tt
                        gg = []
                        for ii in range(mm):
                            for jj in range(dd):
                                gg.append((modulus ** (mm - ii)) * (x ** jj) * (pol ** ii))
                        for ii in range(tt):
                            gg.append((x ** ii) * (pol ** mm))
                        BB = matrix(ZZ, nn)
                        for ii in range(nn):
                            for jj in range(nn):
                                BB[ii, jj] = gg[ii][jj] * (XX ** jj)
                        try:
                            BB = BB.LLL()
                        except (ValueError, RuntimeError):
                            return []
                        new_pol = BB[0][0] * (x ** 0)
                        for ii in range(1, nn):
                            new_pol += (BB[0][ii] // (XX ** ii)) * (x ** ii)
                        roots = []
                        for r, _ in new_pol.roots():
                            if r.is_zero():
                                continue
                            if gcd(modulus, ZZ(pol(r))) >= ZZ(modulus ** beta):
                                roots.append(ZZ(r))
                        return roots
                    # Search phase
                    low = c_prime // 2
                    high = (c_prime + ord_prime) // 2
                    total = Integer(high - low + 1)
                    MAX_ITER = 20
                    found = False
                    if total > MAX_ITER:
                        out.append("Key IS ROCA-vulnerable. Use FactorDB or local Sage:")
                        out.append("  M' = " + str(M_prime))
                        out.append("  c' = " + str(c_prime))
                        out.append("  ord' = " + str(ord_prime))
                        out.append("  X = " + str(X))
                        out.append("  Search range a' in [" + str(low) + ", " + str(high) + "]")
                        out.append("ROCA=FAILED")
                    else:
                        for a_prime in range(low, low + total):
                            r_mod = ZZ(Mod(65537, M_prime) ^ a_prime)
                            known = ZZ(r_mod * inverse_mod(M_prime, n) % n)
                            pol = x + known
                            roots_found = _chu(pol, n, 0.5, mm, tt, X)
                            for k_val in roots_found:
                                p_candidate = ZZ(k_val * M_prime + r_mod)
                                if p_candidate > 1 and p_candidate < n and n % p_candidate == 0:
                                    q_val = n // p_candidate
                                    out.append("p = " + str(p_candidate))
                                    out.append("q = " + str(q_val))
                                    out.append("Verification: p * q = " + str(p_candidate * q_val))
                                    out.append("")
                                    out.append("ROCA=SUCCESS")
                                    found = True
                                    break
                            if found:
                                break
                        if not found:
                            out.append("ROCA=FAILED")
`,
  }),
  proof: `\\textbf{Theorem:} ROCA (Return of Coppersmith's Attack) primes have the form $p = k \\cdot M + (65537^i \\bmod M)$ and are factorable via Coppersmith's method in polynomial time.

\\textbf{Setup:}
\\begin{itemize}
\\item $n = pq$, with primes generated by Infineon's flawed library
\\item $p = k_1 \\cdot M + r_1$, $q = k_2 \\cdot M + r_2$, where $r_i = 65537^{j_i} \\bmod M$
\\item $M$ is a primorial (product of consecutive small primes) with $M > n^{1/4}$
\\item Remainder set $\\mathcal{R} = \\{65537^i \\bmod M : i \\geq 0\\}$ is small (size = ord$_M(65537)$)
\\end{itemize}

\\textbf{Detection:} Since $n \\equiv r_1 r_2 \\pmod{M}$ and $r_1, r_2 \\in \\mathcal{R}$ (a multiplicative subgroup), we have $n \\bmod M \\in \\mathcal{R}$. Checked via discrete logarithm.

\\textbf{Proof:}
\\begin{align*}
n &= (k_1 M + r_1)(k_2 M + r_2) \\\\
n &\\equiv r_1 r_2 \\pmod{M} \\quad \\text{(both remainders in }\\mathcal{R}\\text{)} \\\\
\\text{If } n \\cdot r_2^{-1} \\bmod M &\\in \\mathcal{R}\\text{, then } r_1 = n \\cdot r_2^{-1} \\bmod M \\\\
f(x) &= Mx + r_1 \\equiv 0 \\pmod{p} \\quad\\text{with root } x = k_1 \\\\
|k_1| &< 2\\sqrt{n}/M' < p \\quad\\text{(safety margin factor 2)} \\\\
\\text{Coppersmith (} \\beta = 0.5, X = 2\\sqrt{n}/M' \\text{)} &\\implies k_1 \\text{ found in poly-time} \\\\
p &= M \\cdot k_1 + r_1 \\qed
\\end{align*}

\\textbf{Explanation:} The Infineon RSA key generator had a bug: it generated primes by starting with a random $k$, computing $p = k \\cdot M + (65537^i \\bmod M)$, and testing primality. Since $M$ is large (product of many small primes), the $k$ values are small (often $k < \\sqrt{n}/M \\ll n^{0.5}$), making $p$'s high bits predictable. Coppersmith's theorem says we can find small roots of $f(x) = Mx + r \\bmod p$ when $|x| < p^\\beta$. With $\\beta = 0.5$ and $X = 2\\sqrt{n}/M'$ (factor 2 safety margin), the bounded root $k$ is recovered via lattice reduction (LLL). This attack factored 512-bit keys in minutes and 1024-bit keys in hours in practice.

\\textbf{Optimization:} The greedy M' search reduces the search space by removing prime factors from M that contribute the least order-reduction per M-reduction, yielding a smaller Coppersmith bound $X = 2\\sqrt{n}/M'$.

\\textbf{References:} M. Nemec, M. Sys, P. Svenda, D. Klinec, V. Matyas, "The Return of Coppersmith's Attack: Practical Factorization of Widely Used RSA Moduli", CCS 2017`,
  priority: 'high',
  applicableCheck: (p: Record<string, string>) => !!p.n,
};

export const generateTestcase = (): Record<string, string> => {
  const rocaPrimes = [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n];
  let M = 1n;
  for (const p of rocaPrimes) { M *= p; }
  const kBits = 12;
  for (let attempt = 0; attempt < 5000; attempt++) {
    const i1 = BigInt(Math.floor(Math.random() * 10000));
    const i2 = BigInt(Math.floor(Math.random() * 10000));
    let r1 = modPow(65537n, i1, M);
    let r2 = modPow(65537n, i2, M);
    const kBytes = Math.ceil(kBits / 8);
    const bytes1 = new Uint8Array(kBytes);
    const bytes2 = new Uint8Array(kBytes);
    crypto.getRandomValues(bytes1);
    crypto.getRandomValues(bytes2);
    let k1 = 0n, k2 = 0n;
    for (let j = 0; j < kBytes; j++) {
      k1 = (k1 << 8n) | BigInt(bytes1[j]);
      k2 = (k2 << 8n) | BigInt(bytes2[j]);
    }
    k1 |= (1n << BigInt(kBits - 1)) | 1n;
    k2 |= (1n << BigInt(kBits - 1)) | 1n;
    if (k1 > k2) { [k1, k2] = [k2, k1]; [r1, r2] = [r2, r1]; }
    const p = k1 * M + r1;
    const q = k2 * M + r2;
    if (p > 1 && q > 1 && p !== q && isPrimeMR(p) && isPrimeMR(q)) {
      return { n: (p * q).toString() };
    }
  }
  const pair = generateKeyPair(256, 256);
  return { n: pair.n.toString() };
};
